version: '3'

services:
    # frontend:
    #     build: frontend/.
    #     container_name: frontend
    #     ports: 
    #         - '80:80'
    #     volumes:
    #         - '.:/frontend/app'
    #     networks: 
    #         app-net:
    #             ipv4_address: 172.19.0.2
    
    nginx:
        image: nginx:1.15
        container_name: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks: 
            service_network:
                ipv4_address: 172.35.71.2
        depends_on:
            - backend1
            - backend2
            - backend3

    backend1:
        build: backend/.
        container_name: backend1
        ports: 
            - '5001:5000'
        volumes:
            - '.:/backend/code'
        environment: 
            - SERVNAME=201612272
        networks: 
            service_network:
                ipv4_address: 172.35.71.3
    
    backend2:
        build: backend/.
        container_name: backend2
        ports: 
            - '5002:5000'
        volumes:
            - '.:/backend/code'
        environment: 
            - SERVNAME=201612345
        networks: 
            service_network:
                ipv4_address: 172.35.71.4

    backend3:
        build: backend/.
        container_name: backend3
        ports: 
            - '5003:5000'
        volumes:
            - '.:/backend/code'
        environment: 
            - SERVNAME=201654321
        networks: 
            service_network:
                ipv4_address: 172.35.71.5

    database:
        image: mysql:latest
        container_name: bases-db
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: P4Redes
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - database:/var/lib/mysql
        networks: 
            db_network:
                ipv4_address: 10.10.11.2

networks:
    # frontend_network:
    #     driver: bridge
    #     ipam:
    #         driver: default
    #         config:
    #         - subnet: "192.168.51.0/24"

    service_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.35.71.0/24"

    db_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.10.11.0/24"

volumes:
    database: